name: Python code analysis

on:
    push:
        branches: [ ga/analysis ]
    pull_request:
        branches: [ ga/analysis ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'
                  architecture: 'x64'
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -e .
            - name: Run pylint
              run: |
                  pylint --fail-under=10.0 --exit-zero nlp_research
