name: Python code analysis

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'
                  architecture: 'x64'
            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -e .
            - name: Run pylint
              run: |
                  pylint --config pyproject.toml nlp_research
            - name: Run pycodestyle
              run: |
                   pycodestyle --config pyproject.toml nlp_research
            - name: Run mypy
              run: |
                    mypy --config pyproject.toml nlp_research
