name: Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-root
          poetry self add poetry-exec-plugin
      - name: Run pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: poetry exec pytest
